version: '3.5' 

services: 

    first_volume: 
      image: devopsdockeruh/first_volume_exercise
      volumes: 
        - ./logs.txt:/usr/app/logs.txt
      container_name: first_volume_exercise